Feature - Preliminary BART screen + custom Balloon composable
TaxiKab119/dan-cognition-app pull request #2
Opened 2023-07-18 16:40 UTC by TaxiKab119

The BalloonRatio.kt file was used to make the ratios for the balloon available for various `Box()` sizes as the original canvas drawing was created using a 300.dp box. I am 98% sure the Balloon.kt file will need to be changes to make the code more readable/efficient but I wanted to save some _workable_ progress before moving on.

The navigation setup is crude and doesn't include all the options for categories on the landing screen (which at the moment simply log what button was clicked). The `LandingPageContent()` composable and `NavHost()` / `NavGraphBuilder` will have to be updated accordingly later.

2023-07-18 16:58 UTC, TonyKazanjian commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a preliminary screen for the BART test](https://trello.com/c/ekxKb7vm/3-create-a-preliminary-screen-for-the-bart-test)

2023-07-18 22:18 UTC, TonyKazanjian requested changes

2023-07-18 22:18 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/Balloon.kt
> +): Int {
See above comment

2023-07-18 22:18 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/Balloon.kt
> +    return ((canvasSize / 2.0) - (x / 2.0)).roundToInt()
Have this return a Float, and you won't have to convert to dp and then to px

2023-07-18 22:32 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/BartTestScreen.kt
> +    Column(
As we discussed, let's rewrite this in a ConstraintLayout

2023-07-19 00:32 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/MainActivity.kt
> +                    DanCognitionApp()
Go back to LandingScreen, remove `DanCognitionApp()`

2023-07-20 14:12 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/Balloon.kt
> +    Box(
Resolved from out conversation on Tuesday! I'll push a new Balloon shortly.

2023-07-20 14:17 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/BartTestScreen.kt
> +@Preview(
Sweet that's much better!

2023-07-20 14:19 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/Balloon.kt
> +    return ((canvasSize / 2.0) - (x / 2.0)).roundToInt()
I've now messed around with Float values in the new implementation of Balloon! You're totally right Float is easier...

2023-07-20 16:12 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/ui/LandingPageScreen.kt
> +fun LandingPageScreen(onClick: (Int) -> Unit, modifier: Modifier = Modifier) {
Sweet! I think I understand why "Modifier should be the first optional parameter in the parameter list" if you're using using the trailing lambda syntax. I will double check for this in my next push to try to not have this issue come up again!

2023-07-20 16:15 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/ui/LockScreenOrientation.kt
> +fun LockScreenOrientation(orientation: Int) {
Thanks so much for working on this! I'm currently reading through your PR now and I'm looking up things as I go to try to get the best understanding that I can!

2023-07-20 22:57 UTC, merged