Feature - Use ViewModel and UiState to update BartTestScreen
TaxiKab119/dan-cognition-app pull request #4
Opened 2023-07-23 19:01 UTC by TaxiKab119

This update adds a BartViewModel and a BartUiState to allow for the propagation of state from the UiState to the BartTestScreen. balloonReward and totalEarnings (required for BartTestScreen) were abstracted to the BartUiState class. balloonRadius and initialBalloonRadius could not be abstracted because they depend on the BalloonCanvas Box size. balloonPopped was therefore added to the BartUiState class.

2023-07-24 05:35 UTC, TonyKazanjian requested changes

2023-07-24 05:35 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/BartViewModel.kt
> +            _uiState.value.currentBalloon.maxInflations > _uiState.value.balloonInflations + 1
Double check whether or not you need that + 1 here, because I don't think so. Current inflation count increments after we hit the button, so starting at 0 it should get us to the maximum inflations allowed before it pops. Also, you should check if the balloonList is empty or not before inflating

2023-07-24 05:35 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/BartViewModel.kt
> +    fun collectBalloonReward(reward: Int) {
we already have the reward from the ui state so you don't need to pass it in here. Also make sure to check if the list is empty before updating state.

2023-07-24 05:38 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/data/BalloonGenerator.kt
> +const val MIN_INFLATIONS: Int = 1
Keep these private

2023-07-24 05:44 UTC, TonyKazanjian commented
![](https://github.trello.services/images/mini-trello-icon.png) [Generate Balloons for the BART test](https://trello.com/c/4LZT9svO/9-generate-balloons-for-the-bart-test)

2023-07-24 15:45 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/data/BalloonGenerator.kt
> +    fun getBalloonLinkedList(): LinkedList<Balloon> {
Ok grand this is actually what I wanted to do but I had written the `init{}` block incorrectly and kept running into problems so I just switched to something I knew. Thanks!

To be clear....that piece of code would have to look like this right?

``` 
class BalloonGenerator {
    
    var balloons = LinkedList<Balloon>()
    init {
        balloons = getBalloonLinkedList()
    }

    private fun getBalloonLinkedList(): LinkedList<Balloon> {
...
```
Because `val` can't be reassigned and you're not `init`(ing) anything inside that init block otherwise? I tried your exact version in the Kotlin playground and got those errors but I could be missing something obvious. Please clarify.

2023-07-24 20:40 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/data/BartUiState.kt
> +data class BartUiState(
Ahhhhhh ok so, just for my own clarity, in this case I should be swapping all the items in the data class to `val` and then using `copy` makes more sense because its the best way to update the immutable BartUiState `val`s?

BartUiState:
```
data class BartUiState(
    val balloonList: LinkedList<Balloon>,
    val currentBalloon: Balloon = balloonList.first,
    val currentInflationCount: Int = 0,
    val currentReward: Int = 1,
    val totalEarnings: Int = 0,
    val balloonPopped: Boolean = false
)
```
---------------------------------------------------------------------------------------------
Updating _uiState in ViewModel
```
...
          val updatedState = currentState.copy(
              currentInflationCount = currentState.currentInflationCount.inc(),
              currentReward = currentState.currentReward.inc()
          )
          _uiState.value = updatedState
...
```

2023-07-24 20:58 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/BartViewModel.kt
> +            _uiState.value.currentBalloon.maxInflations > _uiState.value.balloonInflations + 1
Yes you're totally right, I was thinking of the `maxInflations` as more of a `poppingThreshold` so to speak but it would require a person to push one above the `maxInflation` to be pop.

2023-07-25 06:26 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/data/BartUiState.kt
> +data class BartUiState(
Yup, you got it!

2023-07-25 16:38 UTC, TaxiKab119 commented on app/src/main/java/com/example/dancognitionapp/bart/BartViewModel.kt
> +        val isBalloonListEmpty: Boolean = _uiState.value.balloonList.size == 1
I realize that a more fitting name for that variable was probably `isLastBalloon`. 

My intention with the `toNextBalloon()` method was that it would be the final destination after either a collect button press (activating `collectBalloonReward()`) or a final inflation press (activating `inflateBalloon()`). In this case, neither the `collectBalloonReward()` or `inflateBalloon()` methods would ever encounter an empty list because when the list size is 1 the `if (isLastBalloon)` block  in the `toNextBalloon()` method would execute and just end the test.

Hence, `toNextBalloon()` wouldn't run into an empty list (`java.util.NoSuchElementException`) unable to `.removeFirst` anyway. To mitigate this problem further, if on the off chance their was some issue, I've added checks at the start of `CollectBalloonReward()` and `inflateBalloon()` like shown below.

```
...
    fun collectBalloonReward() {
        val isListEmpty: Boolean = balloonList.isEmpty()
        if (isListEmpty) {
            Timber.i("BART completed!")
            return
        }
        val updatedState = currentState.copy(
            totalEarnings = currentState.totalEarnings + currentState.currentReward,
            currentReward = 1,
            currentInflationCount = 0
        )
        _uiState.value = updatedState
        Timber.i("Balloon Number ${currentState.currentBalloon.listPosition} collected!")
        toNextBalloon()
    }
...

```

I have no problem changing the block to the way you've described but it would also change the logic in the `CollectBalloonReward()` and `inflateBalloon()` methods.

2023-07-25 17:55 UTC, TonyKazanjian commented on app/src/main/java/com/example/dancognitionapp/bart/BartViewModel.kt
> +        val isBalloonListEmpty: Boolean = _uiState.value.balloonList.size == 1
```
when the list size is 1 the if (isLastBalloon) block in the toNextBalloon() method would execute and just end the test.
```
I'm not sure I understand here, because if we were to do that, the test would end before the last balloon is able to be inflated and collected. 

I think I see your intention though - we want the test to end just as the last balloon is popped or collected, without the user having to press one of the buttons to get there, right? Let's chat about this in our 1:1 and we'll crank out the behavior we want.

2023-07-26 00:02 UTC, merged